pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                dir('UPES_CONNECT/frontend/') {
                    script {
                        sh 'docker build -t frontdock .'
                        sh 'docker run -p 3000:3000 frontdock'
                    }
                }
            }
        }
    }
}
